name: EAS Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Run quality checks
        run: |
          bun run type-check
          bun run lint
          bun run test

      - name: Build for iOS and Android
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: eas build --platform all --profile preview --non-interactive

      - name: Build for specific platform (manual)
        if: github.event_name == 'workflow_dispatch'
        run: eas build --platform ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --non-interactive

      - name: Build for production (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: eas build --platform all --profile production --non-interactive

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            ~/.expo/logs/
            build-logs/
          retention-days: 7